[profile.default]
src = "src"
out = "out"
test = 'test'
libs = ["lib"]
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]